config/routes.rb
Rails.application.routes.draw do

  root 'landlords#index'

  resources :landlords

end

app/models/landlord.rb
class Landlord < ActiveRecord::Base
  validates :email, presence: true, uniqueness: { case_sensitive: false }
  validates :phone_number, presence: true, uniqueness: { case_sensitive: false }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/landlords_controller.rb
class LandlordsController < ApplicationController

  helper_method :sort_column, :sort_direction

  def index
    @landlords = Landlord.order(sort_column + " " + sort_direction).paginate(per_page: 10, page: params[:page])
  end

  def edit
    @landlord = Landlord.find(params[:id])
  end

  def create
    @landlord = Landlord.new(landlord_params)
    @landlord.save ? landlord_saved : landlord_not_saved
  end

  def new
    @landlord = Landlord.new
  end

  def update
    @landlord = Landlord.find(params[:id])
    @landlord.update_attributes(landlord_params)
    @landlord.save ? landlord_updated : landlord_not_saved
  end

  private

    def landlord_params
      params.require(:landlord).permit(:email, :phone_number, :postcode, :current_rent, :property_price, :yearly_yield, :net_yield, :maintenance_expenses)
    end

    def landlord_updated
      redirect_to landlords_path, notice: "Landlord has been updated."
    end

    def landlord_not_saved
      redirect_to landlords_path, alert: @landlord.errors.full_messages.to_sentence
    end

    def landlord_saved
      redirect_to landlords_path, notice: "New Landlord has been added."
    end

    def sort_column
      Landlord.column_names.include?(params[:sort]) ? params[:sort] : "email"         
    end

    def sort_direction
      %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"      
    end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def flash_class(level)
    style = case level.to_sym
      when :notice then "alert-info"
      when :success then "alert-success"
      when :alert then "alert-danger"
    end
    "alert alert-dismissable " << style
  end

end

app/helpers/landlords_helper.rb
module LandlordsHelper

  def sortable(column, title=nil)
    title ||= column.titleize
    css_class = column == sort_column ? "current #{sort_direction}" : nil
    direction = column == sort_column && sort_direction == "asc" ? "desc" : "asc"
    link_to title, { sort: column, direction: direction }, { class: css_class }
  end

end

app/views/application/_content.html.erb
<div id="content">
  <%= render partial: 'flash_messages' %>
  <div class="container">
    <%= yield %>
  </div>
</div>

app/views/application/_flash_messages.html.erb
<div class="row">
  <div class="col-md-offset-3 col-md-6">
    <% flash.each do |key, message| %>
      <div class="alert-dismissable <%= flash_class key %>" } >
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <p><%= message %></p>
      </div>
    <% end %>
  </div>
</div>

app/views/application/_footer.html.erb
<footer id="footer" class="navbar-fixed-bottom">
  <div class="container">
    <p> &copy; 2014 James Lieu</p>
  </div>
</footer>

app/views/application/_header.html.erb
<div id="header" class="navbar navbar-inverse navbar-static-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <div class="navbar-brand"><%= link_to "Rental Yield Calculator", root_path, id:"home-link" %></div>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li><%= link_to "Landlords", root_path %></li>
      </ul>
    </div>
  </div>
</div>

app/views/landlords/edit.html.erb
<div class="page-header text-center">
  <h1>Edit landlord</h1>
</div>
<div class="col-md-6 col-md-offset-3">
  <div class="panel panel-success">
    <div class="panel-heading">
      <h3 class="panel-title text-center">Edit Landlord</h3>
    </div>
    <div class="panel-body">
      <%= form_for @landlord, method: :put do |f| %>
        <form class="form-horizontal">
          <div class="form-group">
            <%= f.label :email, class: "col-md-4 control-label" %>
            <div class="col-md-8">
              <%= f.email_field :email, required: true, placeholder: "test@example.com", class: "form-control" %>
            </div>
          </div>

          <div class="form-group">
            <%= f.label :phone_number, class: "col-md-4 control-label" %>
            <div class="col-md-8">
              <%= f.number_field :phone_number, required: true, placeholder: "079xxxxxxxxx", class: "form-control" %>
            </div>
          </div>

          <div class="form-group">
            <%= f.label :postcode, class: "col-md-4 control-label"  %>
            <div class="col-md-8">
              <%= f.text_field :postcode, required: true,  placeholder: "NW1 1ER", class: "form-control" %>
            </div>
          </div>

          <div class="form-group">
            <%= f.label "Current Rent", class: "col-md-4 control-label"  %>
            <div class="col-md-8">
              <div class="input-group">
                <span class="input-group-addon">£</span>
                <%= f.number_field :current_rent, required: true, placeholder: "1000",  class: "form-control" , data: { toggle: 'tooltip', title: "The current monthly rent" } %>
              </div>
            </div>
          </div>

          <div class="form-group">
            <%= f.label "Maintenance", class: "col-md-4 control-label"  %>
            <div class="col-md-8">
              <div class="input-group">
                <span class="input-group-addon">£</span>
                <%= f.number_field :maintenance_expenses, value:"0", placeholder: "e.g. Service charge",  class: "form-control", data: { toggle: 'tooltip', title: "The yearly maintenace costs. e.g Servce charge" } %>
              </div>
            </div>
          </div>

          <div class="form-group">
            <%= f.label "Yearly Yield", class: "col-md-4 control-label"  %>
            <div class="col-md-8">
              <div class="input-group">
                <span class="input-group-addon">£</span>
                <%= f.number_field :yearly_yield, readonly:true, class: "form-control", data: { toggle: 'tooltip', title: "This is the yearly yield based on the monthly rent" } %>
              </div>
            </div>
          </div>

          <div class="form-group">
            <%= f.label "Net Yield", class: "col-md-4 control-label"  %>
            <div class="col-md-8">
              <div class="input-group">
                <span class="input-group-addon">£</span>
                <%= f.number_field :net_yield, value: "#landlord_yearly_yield", readonly:true, class: "form-control", data: { toggle: 'tooltip', title: "Rate of return on an investment after subtracting all expenses" } %>
              </div>
            </div>
          </div>

          <div class="form-group">
            <%= f.label :property_price, class: "col-md-4 control-label"  %>
            <div class="col-md-8">
              <div class="input-group">
                <span class="input-group-addon">£</span>
                <%= f.number_field :property_price, required: true, placeholder: "200000",  class: "form-control", data: { toggle: 'tooltip', title: "The total property price" } %>
              </div>
            </div>
          </div>

          <hr>
            <div class="text-center">
              <%= f.submit "Submit", class: "btn btn-success" %>
            </div>
        </form>
      <% end %>
    </div>
  </div>
</div>

app/views/landlords/index.html.erb
<div class="page-header text-center">
  <h1>Landlords</h1>
</div>

<div>
  <table class="table table-striped table-hover table-bordered table-condensed text-center">
    <tr class="success">
      <th><%= sortable "email" %></th>
      <th><%= sortable "phone_number" %></th>
      <th><%= sortable "postcode" %></th>
      <th><%= sortable "current_rent" %></th>
      <th><%= sortable "maintenance_expenses", "Maintenace" %></th>
      <th><%= sortable "yearly_yield" %></th>
      <th><%= sortable "net_yield" %></th>
      <th><%= sortable "property_price" %></th>
      <th></th>
    </tr>
    <% @landlords.each do |landlord| %>
      <tr>
        <td><%= landlord.email %></td>
        <td><%= landlord.phone_number %></td>
        <td><%= landlord.postcode %></td>
        <td><%= number_to_currency(landlord.current_rent, unit: "£") %></td>
        <td><%= number_to_currency(landlord.maintenance_expenses, unit: "£") %></td>
        <td><%= number_to_currency(landlord.yearly_yield, unit: "£") %></td>
        <td><%= number_to_currency(landlord.net_yield, unit: "£") %></td>
        <td><%= number_to_currency(landlord.property_price, unit: "£") %></td>
        <td><%= link_to "Edit", edit_landlord_path(landlord), class:"btn btn-default" %></td>
      </tr>
    <% end %>
  </table>
</div>

<div>
  <%= link_to "New landlord", new_landlord_path,class:"btn btn-success new-button" %>
</div>
<div class="col-md-6 col-md-offset-3 text-center">
  <%= will_paginate @landlords, renderer: BootstrapPagination::Rails %>
</div>

app/views/landlords/new.html.erb
<div class="page-header text-center">
  <h1>New landlord form</h1>
</div>
<div class="col-md-6 col-md-offset-3">
  <div class="panel panel-success">
    <div class="panel-heading">
      <h3 class="panel-title">Enter Landlord Details</h3>
    </div>
    <div class="panel-body">
      <%= form_for @landlord, method: :post do |f| %>
        <form class="form-horizontal">
          <div class="form-group">
            <%= f.label :email, class: "col-md-4 control-label" %>
            <div class="col-md-8">
              <%= f.email_field :email, required: true, placeholder: "test@example.com", class: "form-control", data: { toggle: 'tooltip', title: "Please enter your email" } %>
            </div>
          </div>

          <div class="form-group">
            <%= f.label :phone_number, class: "col-md-4 control-label" %>
            <div class="col-md-8">
              <%= f.number_field :phone_number, required: true, placeholder: "079xxxxxxxxx", class: "form-control", data: { toggle: 'tooltip', title: "Please enter your phone number" } %>
            </div>
          </div>

          <div class="form-group">
            <%= f.label :postcode, class: "col-md-4 control-label"  %>
            <div class="col-md-8">
              <%= f.text_field :postcode, required: true,  placeholder: "NW1 1ER", class: "form-control", data: { toggle: 'tooltip', title: "Please enter your postcode" } %>
            </div>
          </div>

          <div class="form-group">
            <%= f.label "Current Rent", class: "col-md-4 control-label"  %>
            <div class="col-md-8">
              <div class="input-group">
                <span class="input-group-addon">£</span>
                <%= f.number_field :current_rent, required: true, placeholder: "1000",  class: "form-control" , data: { toggle: 'tooltip', title: "Please enter the current monthly rent" } %>
              </div>
            </div>
          </div>

          <div class="form-group">
            <%= f.label "Maintenance", class: "col-md-4 control-label"  %>
            <div class="col-md-8">
              <div class="input-group">
                <span class="input-group-addon">£</span>
                <%= f.number_field :maintenance_expenses, value:"0", placeholder: "e.g. Service charge",  class: "form-control", data: { toggle: 'tooltip', title: "Please enter the yearly maintenace costs. e.g Servce charge" } %>
              </div>
            </div>
          </div>

          <div class="form-group">
            <%= f.label "Yearly Yield", class: "col-md-4 control-label"  %>
            <div class="col-md-8">
              <div class="input-group">
                <span class="input-group-addon">£</span>
                <%= f.number_field :yearly_yield, readonly:true, class: "form-control", data: { toggle: 'tooltip', title: "This is the yearly yield based on the monthly rent" } %>
              </div>
            </div>
          </div>

          <div class="form-group">
            <%= f.label "Net Yield", class: "col-md-4 control-label"  %>
            <div class="col-md-8">
              <div class="input-group">
                <span class="input-group-addon">£</span>
                <%= f.number_field :net_yield, value: "#landlord_yearly_yield", readonly:true, class: "form-control", data: { toggle: 'tooltip', title: "Rate of return on an investment after subtracting all expenses" } %>
              </div>
            </div>
          </div>

          <div class="form-group">
            <%= f.label :property_price, class: "col-md-4 control-label"  %>
            <div class="col-md-8">
              <div class="input-group">
                <span class="input-group-addon">£</span>
                <%= f.number_field :property_price, required: true, placeholder: "200000",  class: "form-control", data: { toggle: 'tooltip', title: "The total property price" } %>
              </div>
            </div>
          </div>

          <hr>
            <div class="text-center">
              <%= f.submit "Submit", class: "btn btn-success" %>
            </div>
        </form>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">

  <script src="http://code.jquery.com/jquery-1.9.1.js"></script>
  <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>

  <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
  <script src="http://code.jquery.com/ui/1.10.3/jquery-ui.js"></script>

  <title>Rental yield calculator</title>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>

</head>
<body>

  <%= render 'header' %>
  <%= render 'content' %>
  <%= render 'footer' %>

  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

</body>
</html>